# Use postgres/example user/password credentials

env_file:
  - ./../.env

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
